build:
  environment:
    php: 7.4
    timezone: Europe/Paris
    variables:
      ELASTICSEARCH_HOST: '127.0.0.1:9200'

  nodes:
    tests:
      services:
        elasticsearch: 7.17.1

      tests:
        override:
          - command: composer require --dev 'elasticsearch/elasticsearch:~7.0' --with-all-dependencies
          - command: composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover
