parameters:
    prime.indexer.configuration: []
    prime.indexer.configuration.elasticsearch: []

services:
    Elasticsearch\Client:
        deprecated:
            package: 'b2pweb/bdf-prime-indexer'
            version: 2.0
            message: 'Direct usage of elasticsearch driver client using service "%service_id%" is deprecated since 2.0'
        factory: ['@Bdf\Prime\Indexer\Elasticsearch\Adapter\ClientInterface', 'getInternalClient']
        public: true

    Bdf\Prime\Indexer\Elasticsearch\Adapter\ClientInterface:
        class: Bdf\Prime\Indexer\Elasticsearch\Adapter\ClientInterface
        public: true
        factory: [ 'Bdf\Prime\Indexer\Elasticsearch\Adapter\ClientFactory', 'fromArray' ]
        arguments:
            - '%prime.indexer.configuration.elasticsearch%'

    Bdf\Prime\Indexer\Resolver\MappingResolver:
        class: Bdf\Prime\Indexer\Resolver\MappingResolver
        arguments: ['@service_container']
        public: true

    Bdf\Prime\Indexer\IndexFactory:
        class: Bdf\Prime\Indexer\IndexFactory
        arguments:
            - []
            - '@Bdf\Prime\Indexer\Resolver\MappingResolver'
        public: true

    Bdf\Prime\Indexer\Bundle\Factory\ElasticsearchIndexFactory:
        class: Bdf\Prime\Indexer\Bundle\Factory\ElasticsearchIndexFactory
        arguments: ['@service_container']
        tags: ['prime.indexer.factory']

    Bdf\Prime\Indexer\Bundle\Factory\DenormalizerIndexFactory:
        class: Bdf\Prime\Indexer\Bundle\Factory\DenormalizerIndexFactory
        tags: ['prime.indexer.factory']

    # Commands
    Bdf\Prime\Indexer\Elasticsearch\Console\ShowCommand:
        class: Bdf\Prime\Indexer\Elasticsearch\Console\ShowCommand
        arguments:
            - '@Bdf\Prime\Indexer\Elasticsearch\Adapter\ClientInterface'
            - '%prime.indexer.configuration%'
        tags: ['console.command']

    Bdf\Prime\Indexer\Elasticsearch\Console\DeleteCommand:
        class: Bdf\Prime\Indexer\Elasticsearch\Console\DeleteCommand
        arguments:
            - '@Bdf\Prime\Indexer\Elasticsearch\Adapter\ClientInterface'
            - '%prime.indexer.configuration%'
        tags: ['console.command']

    Bdf\Prime\Indexer\Console\CreateIndexCommand:
        class: Bdf\Prime\Indexer\Console\CreateIndexCommand
        arguments:
            - '@Bdf\Prime\Indexer\IndexFactory'
            - '@Bdf\Prime\ServiceLocator'
            - '@logger'
        tags: ['console.command']

    # Messenger
    Bdf\Prime\Indexer\Sync\AddToIndexHandler:
        class: Bdf\Prime\Indexer\Sync\AddToIndexHandler
        arguments: ['@Bdf\Prime\Indexer\IndexFactory']
        tags: [messenger.message_handler]

    Bdf\Prime\Indexer\Sync\RemoveFromIndexHandler:
        class: Bdf\Prime\Indexer\Sync\RemoveFromIndexHandler
        arguments: ['@Bdf\Prime\Indexer\IndexFactory']
        tags: [messenger.message_handler]

    Bdf\Prime\Indexer\Sync\UpdateIndexedEntityHandler:
        class: Bdf\Prime\Indexer\Sync\UpdateIndexedEntityHandler
        arguments: ['@Bdf\Prime\Indexer\IndexFactory']
        tags: [messenger.message_handler]
