name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ELASTICSEARCH_HOST: '127.0.0.1:9200'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Paris"
    
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: json
        ini-values: date.timezone=Europe/Paris
    - name: Check PHP Version
      run: php -v

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - uses: nyaruka/elasticsearch-action@v1
      with:
        elastic version: '2.4'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script tests

  es_compatiblity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        es-versions: ['2.4', '5.6']
    name: Elasticsearch version ${{ matrix.es-versions }}

    steps:
    - uses: actions/checkout@v2

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Paris"

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2
        extensions: json
        ini-values: date.timezone=Europe/Paris

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - uses: nyaruka/elasticsearch-action@v1
      with:
        elastic version: ${{ matrix.es-versions }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script tests

  analysis:
    name: Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Paris"

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: json
        ini-values: date.timezone=Europe/Paris
#
#    - name: Install Infection
#      run: composer global require infection/infection

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run type coverage
      run: composer run-script psalm

#    - name: Run Infection
#      run: |
#        git fetch --depth=1 origin $GITHUB_BASE_REF
#        ~/.composer/vendor/bin/infection --logger-github --git-diff-filter=AM
